AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    OpenApiVersion: '3.0.1'

Resources:
  NodeTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template-function.yaml

  PythonTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./hello-world-python.yaml

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      MethodSettings:
        - DataTraceEnabled: false
          MetricsEnabled: false
          ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
      Cors:
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET'"
        AllowOrigin: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: api.yaml

  HelloWorldLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt NodeTemplate.Outputs.HelloWorldFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/GET/node"

  HelloWorldPythonLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PythonTemplate.Outputs.HelloWorldPythonFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/GET/python"

Outputs:
  Endpoint:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${Api}.execute-api.${AWS::Region}.amazonaws.com/

